// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: common.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrequencyType int32

const (
	FrequencyType_FREQUENCY_TYPE_UNSPECIFIED FrequencyType = 0
	FrequencyType_FREQUENCY_TYPE_ONCE        FrequencyType = 1
	FrequencyType_FREQUENCY_TYPE_DAILY       FrequencyType = 2
	FrequencyType_FREQUENCY_TYPE_WEEKLY      FrequencyType = 3
	FrequencyType_FREQUENCY_TYPE_MONTHLY     FrequencyType = 4
	FrequencyType_FREQUENCY_TYPE_YEARLY      FrequencyType = 5
	FrequencyType_FREQUENCY_TYPE_CUSTOM      FrequencyType = 6
)

// Enum value maps for FrequencyType.
var (
	FrequencyType_name = map[int32]string{
		0: "FREQUENCY_TYPE_UNSPECIFIED",
		1: "FREQUENCY_TYPE_ONCE",
		2: "FREQUENCY_TYPE_DAILY",
		3: "FREQUENCY_TYPE_WEEKLY",
		4: "FREQUENCY_TYPE_MONTHLY",
		5: "FREQUENCY_TYPE_YEARLY",
		6: "FREQUENCY_TYPE_CUSTOM",
	}
	FrequencyType_value = map[string]int32{
		"FREQUENCY_TYPE_UNSPECIFIED": 0,
		"FREQUENCY_TYPE_ONCE":        1,
		"FREQUENCY_TYPE_DAILY":       2,
		"FREQUENCY_TYPE_WEEKLY":      3,
		"FREQUENCY_TYPE_MONTHLY":     4,
		"FREQUENCY_TYPE_YEARLY":      5,
		"FREQUENCY_TYPE_CUSTOM":      6,
	}
)

func (x FrequencyType) Enum() *FrequencyType {
	p := new(FrequencyType)
	*p = x
	return p
}

func (x FrequencyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrequencyType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (FrequencyType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x FrequencyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrequencyType.Descriptor instead.
func (FrequencyType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type IntervalUnit int32

const (
	IntervalUnit_INTERVAL_UNIT_UNSPECIFIED IntervalUnit = 0
	IntervalUnit_INTERVAL_UNIT_HOURS       IntervalUnit = 1
	IntervalUnit_INTERVAL_UNIT_DAYS        IntervalUnit = 2
	IntervalUnit_INTERVAL_UNIT_WEEKS       IntervalUnit = 3
	IntervalUnit_INTERVAL_UNIT_MONTHS      IntervalUnit = 4
	IntervalUnit_INTERVAL_UNIT_YEARS       IntervalUnit = 5
)

// Enum value maps for IntervalUnit.
var (
	IntervalUnit_name = map[int32]string{
		0: "INTERVAL_UNIT_UNSPECIFIED",
		1: "INTERVAL_UNIT_HOURS",
		2: "INTERVAL_UNIT_DAYS",
		3: "INTERVAL_UNIT_WEEKS",
		4: "INTERVAL_UNIT_MONTHS",
		5: "INTERVAL_UNIT_YEARS",
	}
	IntervalUnit_value = map[string]int32{
		"INTERVAL_UNIT_UNSPECIFIED": 0,
		"INTERVAL_UNIT_HOURS":       1,
		"INTERVAL_UNIT_DAYS":        2,
		"INTERVAL_UNIT_WEEKS":       3,
		"INTERVAL_UNIT_MONTHS":      4,
		"INTERVAL_UNIT_YEARS":       5,
	}
)

func (x IntervalUnit) Enum() *IntervalUnit {
	p := new(IntervalUnit)
	*p = x
	return p
}

func (x IntervalUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntervalUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (IntervalUnit) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x IntervalUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntervalUnit.Descriptor instead.
func (IntervalUnit) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type RepeatOn int32

const (
	RepeatOn_REPEAT_ON_UNSPECIFIED       RepeatOn = 0
	RepeatOn_REPEAT_ON_INTERVAL          RepeatOn = 1
	RepeatOn_REPEAT_ON_DAYS_OF_THE_WEEK  RepeatOn = 2
	RepeatOn_REPEAT_ON_DAY_OF_THE_MONTHS RepeatOn = 3
)

// Enum value maps for RepeatOn.
var (
	RepeatOn_name = map[int32]string{
		0: "REPEAT_ON_UNSPECIFIED",
		1: "REPEAT_ON_INTERVAL",
		2: "REPEAT_ON_DAYS_OF_THE_WEEK",
		3: "REPEAT_ON_DAY_OF_THE_MONTHS",
	}
	RepeatOn_value = map[string]int32{
		"REPEAT_ON_UNSPECIFIED":       0,
		"REPEAT_ON_INTERVAL":          1,
		"REPEAT_ON_DAYS_OF_THE_WEEK":  2,
		"REPEAT_ON_DAY_OF_THE_MONTHS": 3,
	}
)

func (x RepeatOn) Enum() *RepeatOn {
	p := new(RepeatOn)
	*p = x
	return p
}

func (x RepeatOn) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepeatOn) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (RepeatOn) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x RepeatOn) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepeatOn.Descriptor instead.
func (RepeatOn) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type NotificationProviderType int32

const (
	NotificationProviderType_NOTIFICATION_PROVIDER_NONE    NotificationProviderType = 0
	NotificationProviderType_NOTIFICATION_PROVIDER_WEBHOOK NotificationProviderType = 1
	NotificationProviderType_NOTIFICATION_PROVIDER_GOTIFY  NotificationProviderType = 2
)

// Enum value maps for NotificationProviderType.
var (
	NotificationProviderType_name = map[int32]string{
		0: "NOTIFICATION_PROVIDER_NONE",
		1: "NOTIFICATION_PROVIDER_WEBHOOK",
		2: "NOTIFICATION_PROVIDER_GOTIFY",
	}
	NotificationProviderType_value = map[string]int32{
		"NOTIFICATION_PROVIDER_NONE":    0,
		"NOTIFICATION_PROVIDER_WEBHOOK": 1,
		"NOTIFICATION_PROVIDER_GOTIFY":  2,
	}
)

func (x NotificationProviderType) Enum() *NotificationProviderType {
	p := new(NotificationProviderType)
	*p = x
	return p
}

func (x NotificationProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (NotificationProviderType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x NotificationProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationProviderType.Descriptor instead.
func (NotificationProviderType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_DUE_DATE    NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_PRE_DUE     NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_OVERDUE     NotificationType = 3
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_DUE_DATE",
		2: "NOTIFICATION_TYPE_PRE_DUE",
		3: "NOTIFICATION_TYPE_OVERDUE",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"NOTIFICATION_TYPE_DUE_DATE":    1,
		"NOTIFICATION_TYPE_PRE_DUE":     2,
		"NOTIFICATION_TYPE_OVERDUE":     3,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

type ApiTokenScope int32

const (
	ApiTokenScope_API_TOKEN_SCOPE_UNSPECIFIED ApiTokenScope = 0
	ApiTokenScope_API_TOKEN_SCOPE_TASK_READ   ApiTokenScope = 1
	ApiTokenScope_API_TOKEN_SCOPE_TASK_WRITE  ApiTokenScope = 2
	ApiTokenScope_API_TOKEN_SCOPE_LABEL_READ  ApiTokenScope = 3
	ApiTokenScope_API_TOKEN_SCOPE_LABEL_WRITE ApiTokenScope = 4
	ApiTokenScope_API_TOKEN_SCOPE_USER_READ   ApiTokenScope = 5
	ApiTokenScope_API_TOKEN_SCOPE_USER_WRITE  ApiTokenScope = 6
	ApiTokenScope_API_TOKEN_SCOPE_TOKEN_WRITE ApiTokenScope = 7
	ApiTokenScope_API_TOKEN_SCOPE_DAV_READ    ApiTokenScope = 8
	ApiTokenScope_API_TOKEN_SCOPE_DAV_WRITE   ApiTokenScope = 9
)

// Enum value maps for ApiTokenScope.
var (
	ApiTokenScope_name = map[int32]string{
		0: "API_TOKEN_SCOPE_UNSPECIFIED",
		1: "API_TOKEN_SCOPE_TASK_READ",
		2: "API_TOKEN_SCOPE_TASK_WRITE",
		3: "API_TOKEN_SCOPE_LABEL_READ",
		4: "API_TOKEN_SCOPE_LABEL_WRITE",
		5: "API_TOKEN_SCOPE_USER_READ",
		6: "API_TOKEN_SCOPE_USER_WRITE",
		7: "API_TOKEN_SCOPE_TOKEN_WRITE",
		8: "API_TOKEN_SCOPE_DAV_READ",
		9: "API_TOKEN_SCOPE_DAV_WRITE",
	}
	ApiTokenScope_value = map[string]int32{
		"API_TOKEN_SCOPE_UNSPECIFIED": 0,
		"API_TOKEN_SCOPE_TASK_READ":   1,
		"API_TOKEN_SCOPE_TASK_WRITE":  2,
		"API_TOKEN_SCOPE_LABEL_READ":  3,
		"API_TOKEN_SCOPE_LABEL_WRITE": 4,
		"API_TOKEN_SCOPE_USER_READ":   5,
		"API_TOKEN_SCOPE_USER_WRITE":  6,
		"API_TOKEN_SCOPE_TOKEN_WRITE": 7,
		"API_TOKEN_SCOPE_DAV_READ":    8,
		"API_TOKEN_SCOPE_DAV_WRITE":   9,
	}
)

func (x ApiTokenScope) Enum() *ApiTokenScope {
	p := new(ApiTokenScope)
	*p = x
	return p
}

func (x ApiTokenScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiTokenScope) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[5].Descriptor()
}

func (ApiTokenScope) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[5]
}

func (x ApiTokenScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiTokenScope.Descriptor instead.
func (ApiTokenScope) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

type Frequency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FrequencyType          `protobuf:"varint,1,opt,name=type,proto3,enum=com.dkhalife.tasks.grpc.FrequencyType" json:"type,omitempty"`
	On            RepeatOn               `protobuf:"varint,2,opt,name=on,proto3,enum=com.dkhalife.tasks.grpc.RepeatOn" json:"on,omitempty"`
	Every         int32                  `protobuf:"varint,3,opt,name=every,proto3" json:"every,omitempty"`
	Unit          IntervalUnit           `protobuf:"varint,4,opt,name=unit,proto3,enum=com.dkhalife.tasks.grpc.IntervalUnit" json:"unit,omitempty"`
	Days          []int32                `protobuf:"varint,5,rep,packed,name=days,proto3" json:"days,omitempty"`
	Months        []int32                `protobuf:"varint,6,rep,packed,name=months,proto3" json:"months,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frequency) Reset() {
	*x = Frequency{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frequency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frequency) ProtoMessage() {}

func (x *Frequency) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frequency.ProtoReflect.Descriptor instead.
func (*Frequency) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Frequency) GetType() FrequencyType {
	if x != nil {
		return x.Type
	}
	return FrequencyType_FREQUENCY_TYPE_UNSPECIFIED
}

func (x *Frequency) GetOn() RepeatOn {
	if x != nil {
		return x.On
	}
	return RepeatOn_REPEAT_ON_UNSPECIFIED
}

func (x *Frequency) GetEvery() int32 {
	if x != nil {
		return x.Every
	}
	return 0
}

func (x *Frequency) GetUnit() IntervalUnit {
	if x != nil {
		return x.Unit
	}
	return IntervalUnit_INTERVAL_UNIT_UNSPECIFIED
}

func (x *Frequency) GetDays() []int32 {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *Frequency) GetMonths() []int32 {
	if x != nil {
		return x.Months
	}
	return nil
}

type NotificationTriggerOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DueDate       bool                   `protobuf:"varint,2,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	PreDue        bool                   `protobuf:"varint,3,opt,name=pre_due,json=preDue,proto3" json:"pre_due,omitempty"`
	Overdue       bool                   `protobuf:"varint,4,opt,name=overdue,proto3" json:"overdue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationTriggerOptions) Reset() {
	*x = NotificationTriggerOptions{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTriggerOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTriggerOptions) ProtoMessage() {}

func (x *NotificationTriggerOptions) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTriggerOptions.ProtoReflect.Descriptor instead.
func (*NotificationTriggerOptions) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationTriggerOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NotificationTriggerOptions) GetDueDate() bool {
	if x != nil {
		return x.DueDate
	}
	return false
}

func (x *NotificationTriggerOptions) GetPreDue() bool {
	if x != nil {
		return x.PreDue
	}
	return false
}

func (x *NotificationTriggerOptions) GetOverdue() bool {
	if x != nil {
		return x.Overdue
	}
	return false
}

type NotificationProvider struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Provider      NotificationProviderType `protobuf:"varint,1,opt,name=provider,proto3,enum=com.dkhalife.tasks.grpc.NotificationProviderType" json:"provider,omitempty"`
	Url           string                   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Token         string                   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationProvider) Reset() {
	*x = NotificationProvider{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationProvider) ProtoMessage() {}

func (x *NotificationProvider) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationProvider.ProtoReflect.Descriptor instead.
func (*NotificationProvider) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationProvider) GetProvider() NotificationProviderType {
	if x != nil {
		return x.Provider
	}
	return NotificationProviderType_NOTIFICATION_PROVIDER_NONE
}

func (x *NotificationProvider) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NotificationProvider) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NotificationProvider) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x17com.dkhalife.tasks.grpc\"\xf7\x01\n" +
	"\tFrequency\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.com.dkhalife.tasks.grpc.FrequencyTypeR\x04type\x121\n" +
	"\x02on\x18\x02 \x01(\x0e2!.com.dkhalife.tasks.grpc.RepeatOnR\x02on\x12\x14\n" +
	"\x05every\x18\x03 \x01(\x05R\x05every\x129\n" +
	"\x04unit\x18\x04 \x01(\x0e2%.com.dkhalife.tasks.grpc.IntervalUnitR\x04unit\x12\x12\n" +
	"\x04days\x18\x05 \x03(\x05R\x04days\x12\x16\n" +
	"\x06months\x18\x06 \x03(\x05R\x06months\"\x84\x01\n" +
	"\x1aNotificationTriggerOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x19\n" +
	"\bdue_date\x18\x02 \x01(\bR\adueDate\x12\x17\n" +
	"\apre_due\x18\x03 \x01(\bR\x06preDue\x12\x18\n" +
	"\aoverdue\x18\x04 \x01(\bR\aoverdue\"\xa5\x01\n" +
	"\x14NotificationProvider\x12M\n" +
	"\bprovider\x18\x01 \x01(\x0e21.com.dkhalife.tasks.grpc.NotificationProviderTypeR\bprovider\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\a\n" +
	"\x05Empty*\xcf\x01\n" +
	"\rFrequencyType\x12\x1e\n" +
	"\x1aFREQUENCY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FREQUENCY_TYPE_ONCE\x10\x01\x12\x18\n" +
	"\x14FREQUENCY_TYPE_DAILY\x10\x02\x12\x19\n" +
	"\x15FREQUENCY_TYPE_WEEKLY\x10\x03\x12\x1a\n" +
	"\x16FREQUENCY_TYPE_MONTHLY\x10\x04\x12\x19\n" +
	"\x15FREQUENCY_TYPE_YEARLY\x10\x05\x12\x19\n" +
	"\x15FREQUENCY_TYPE_CUSTOM\x10\x06*\xaa\x01\n" +
	"\fIntervalUnit\x12\x1d\n" +
	"\x19INTERVAL_UNIT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13INTERVAL_UNIT_HOURS\x10\x01\x12\x16\n" +
	"\x12INTERVAL_UNIT_DAYS\x10\x02\x12\x17\n" +
	"\x13INTERVAL_UNIT_WEEKS\x10\x03\x12\x18\n" +
	"\x14INTERVAL_UNIT_MONTHS\x10\x04\x12\x17\n" +
	"\x13INTERVAL_UNIT_YEARS\x10\x05*~\n" +
	"\bRepeatOn\x12\x19\n" +
	"\x15REPEAT_ON_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12REPEAT_ON_INTERVAL\x10\x01\x12\x1e\n" +
	"\x1aREPEAT_ON_DAYS_OF_THE_WEEK\x10\x02\x12\x1f\n" +
	"\x1bREPEAT_ON_DAY_OF_THE_MONTHS\x10\x03*\x7f\n" +
	"\x18NotificationProviderType\x12\x1e\n" +
	"\x1aNOTIFICATION_PROVIDER_NONE\x10\x00\x12!\n" +
	"\x1dNOTIFICATION_PROVIDER_WEBHOOK\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_PROVIDER_GOTIFY\x10\x02*\x93\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_TYPE_DUE_DATE\x10\x01\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_PRE_DUE\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_OVERDUE\x10\x03*\xcd\x02\n" +
	"\rApiTokenScope\x12\x1f\n" +
	"\x1bAPI_TOKEN_SCOPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19API_TOKEN_SCOPE_TASK_READ\x10\x01\x12\x1e\n" +
	"\x1aAPI_TOKEN_SCOPE_TASK_WRITE\x10\x02\x12\x1e\n" +
	"\x1aAPI_TOKEN_SCOPE_LABEL_READ\x10\x03\x12\x1f\n" +
	"\x1bAPI_TOKEN_SCOPE_LABEL_WRITE\x10\x04\x12\x1d\n" +
	"\x19API_TOKEN_SCOPE_USER_READ\x10\x05\x12\x1e\n" +
	"\x1aAPI_TOKEN_SCOPE_USER_WRITE\x10\x06\x12\x1f\n" +
	"\x1bAPI_TOKEN_SCOPE_TOKEN_WRITE\x10\a\x12\x1c\n" +
	"\x18API_TOKEN_SCOPE_DAV_READ\x10\b\x12\x1d\n" +
	"\x19API_TOKEN_SCOPE_DAV_WRITE\x10\tBT\n" +
	"\x17com.dkhalife.tasks.grpcB\vCommonProtoZ,github.com/dkhalife/task-wizard/servers/grpcb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(FrequencyType)(0),                 // 0: com.dkhalife.tasks.grpc.FrequencyType
	(IntervalUnit)(0),                  // 1: com.dkhalife.tasks.grpc.IntervalUnit
	(RepeatOn)(0),                      // 2: com.dkhalife.tasks.grpc.RepeatOn
	(NotificationProviderType)(0),      // 3: com.dkhalife.tasks.grpc.NotificationProviderType
	(NotificationType)(0),              // 4: com.dkhalife.tasks.grpc.NotificationType
	(ApiTokenScope)(0),                 // 5: com.dkhalife.tasks.grpc.ApiTokenScope
	(*Frequency)(nil),                  // 6: com.dkhalife.tasks.grpc.Frequency
	(*NotificationTriggerOptions)(nil), // 7: com.dkhalife.tasks.grpc.NotificationTriggerOptions
	(*NotificationProvider)(nil),       // 8: com.dkhalife.tasks.grpc.NotificationProvider
	(*Empty)(nil),                      // 9: com.dkhalife.tasks.grpc.Empty
}
var file_common_proto_depIdxs = []int32{
	0, // 0: com.dkhalife.tasks.grpc.Frequency.type:type_name -> com.dkhalife.tasks.grpc.FrequencyType
	2, // 1: com.dkhalife.tasks.grpc.Frequency.on:type_name -> com.dkhalife.tasks.grpc.RepeatOn
	1, // 2: com.dkhalife.tasks.grpc.Frequency.unit:type_name -> com.dkhalife.tasks.grpc.IntervalUnit
	3, // 3: com.dkhalife.tasks.grpc.NotificationProvider.provider:type_name -> com.dkhalife.tasks.grpc.NotificationProviderType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
