// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: task_service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_task_service_proto protoreflect.FileDescriptor

const file_task_service_proto_rawDesc = "" +
	"\n" +
	"\x12task_service.proto\x12\x17com.dkhalife.tasks.grpc\x1a\fcommon.proto\x1a\n" +
	"task.proto\x1a\vlabel.proto\x1a\n" +
	"user.proto2\xe0\b\n" +
	"\vTaskService\x12T\n" +
	"\bGetTasks\x12\x1e.com.dkhalife.tasks.grpc.Empty\x1a&.com.dkhalife.tasks.grpc.TasksResponse\"\x00\x12p\n" +
	"\x11GetCompletedTasks\x121.com.dkhalife.tasks.grpc.GetCompletedTasksRequest\x1a&.com.dkhalife.tasks.grpc.TasksResponse\"\x00\x12[\n" +
	"\aGetTask\x12'.com.dkhalife.tasks.grpc.GetTaskRequest\x1a%.com.dkhalife.tasks.grpc.TaskResponse\"\x00\x12a\n" +
	"\n" +
	"CreateTask\x12*.com.dkhalife.tasks.grpc.CreateTaskRequest\x1a%.com.dkhalife.tasks.grpc.TaskResponse\"\x00\x12a\n" +
	"\n" +
	"UpdateTask\x12*.com.dkhalife.tasks.grpc.UpdateTaskRequest\x1a%.com.dkhalife.tasks.grpc.TaskResponse\"\x00\x12Z\n" +
	"\n" +
	"DeleteTask\x12*.com.dkhalife.tasks.grpc.DeleteTaskRequest\x1a\x1e.com.dkhalife.tasks.grpc.Empty\"\x00\x12e\n" +
	"\fCompleteTask\x12,.com.dkhalife.tasks.grpc.CompleteTaskRequest\x1a%.com.dkhalife.tasks.grpc.TaskResponse\"\x00\x12i\n" +
	"\x0eUncompleteTask\x12..com.dkhalife.tasks.grpc.UncompleteTaskRequest\x1a%.com.dkhalife.tasks.grpc.TaskResponse\"\x00\x12]\n" +
	"\bSkipTask\x12(.com.dkhalife.tasks.grpc.SkipTaskRequest\x1a%.com.dkhalife.tasks.grpc.TaskResponse\"\x00\x12g\n" +
	"\rUpdateDueDate\x12-.com.dkhalife.tasks.grpc.UpdateDueDateRequest\x1a%.com.dkhalife.tasks.grpc.TaskResponse\"\x00\x12p\n" +
	"\x0eGetTaskHistory\x12..com.dkhalife.tasks.grpc.GetTaskHistoryRequest\x1a,.com.dkhalife.tasks.grpc.TaskHistoryResponse\"\x002\x90\x03\n" +
	"\fLabelService\x12V\n" +
	"\tGetLabels\x12\x1e.com.dkhalife.tasks.grpc.Empty\x1a'.com.dkhalife.tasks.grpc.LabelsResponse\"\x00\x12d\n" +
	"\vCreateLabel\x12+.com.dkhalife.tasks.grpc.CreateLabelRequest\x1a&.com.dkhalife.tasks.grpc.LabelResponse\"\x00\x12d\n" +
	"\vUpdateLabel\x12+.com.dkhalife.tasks.grpc.UpdateLabelRequest\x1a&.com.dkhalife.tasks.grpc.LabelResponse\"\x00\x12\\\n" +
	"\vDeleteLabel\x12+.com.dkhalife.tasks.grpc.DeleteLabelRequest\x1a\x1e.com.dkhalife.tasks.grpc.Empty\"\x002\xcb\x02\n" +
	"\vUserService\x12\\\n" +
	"\n" +
	"GetProfile\x12\x1e.com.dkhalife.tasks.grpc.Empty\x1a,.com.dkhalife.tasks.grpc.UserProfileResponse\"\x00\x12z\n" +
	"\x1aUpdateNotificationSettings\x12:.com.dkhalife.tasks.grpc.UpdateNotificationSettingsRequest\x1a\x1e.com.dkhalife.tasks.grpc.Empty\"\x00\x12b\n" +
	"\x0eChangePassword\x12..com.dkhalife.tasks.grpc.ChangePasswordRequest\x1a\x1e.com.dkhalife.tasks.grpc.Empty\"\x002\xbf\x02\n" +
	"\fTokenService\x12\\\n" +
	"\fGetAppTokens\x12\x1e.com.dkhalife.tasks.grpc.Empty\x1a*.com.dkhalife.tasks.grpc.AppTokensResponse\"\x00\x12m\n" +
	"\x0eCreateAppToken\x12..com.dkhalife.tasks.grpc.CreateAppTokenRequest\x1a).com.dkhalife.tasks.grpc.AppTokenResponse\"\x00\x12b\n" +
	"\x0eDeleteAppToken\x12..com.dkhalife.tasks.grpc.DeleteAppTokenRequest\x1a\x1e.com.dkhalife.tasks.grpc.Empty\"\x002\xe7\x03\n" +
	"\vAuthService\x12R\n" +
	"\x06SignUp\x12&.com.dkhalife.tasks.grpc.SignUpRequest\x1a\x1e.com.dkhalife.tasks.grpc.Empty\"\x00\x12W\n" +
	"\x05Login\x12%.com.dkhalife.tasks.grpc.LoginRequest\x1a%.com.dkhalife.tasks.grpc.AuthResponse\"\x00\x12e\n" +
	"\fRefreshToken\x12,.com.dkhalife.tasks.grpc.RefreshTokenRequest\x1a%.com.dkhalife.tasks.grpc.AuthResponse\"\x00\x12`\n" +
	"\rResetPassword\x12-.com.dkhalife.tasks.grpc.ResetPasswordRequest\x1a\x1e.com.dkhalife.tasks.grpc.Empty\"\x00\x12b\n" +
	"\x0eUpdatePassword\x12..com.dkhalife.tasks.grpc.UpdatePasswordRequest\x1a\x1e.com.dkhalife.tasks.grpc.Empty\"\x00BY\n" +
	"\x17com.dkhalife.tasks.grpcB\x10TaskServiceProtoZ,github.com/dkhalife/task-wizard/servers/grpcb\x06proto3"

var file_task_service_proto_goTypes = []any{
	(*Empty)(nil),                             // 0: com.dkhalife.tasks.grpc.Empty
	(*GetCompletedTasksRequest)(nil),          // 1: com.dkhalife.tasks.grpc.GetCompletedTasksRequest
	(*GetTaskRequest)(nil),                    // 2: com.dkhalife.tasks.grpc.GetTaskRequest
	(*CreateTaskRequest)(nil),                 // 3: com.dkhalife.tasks.grpc.CreateTaskRequest
	(*UpdateTaskRequest)(nil),                 // 4: com.dkhalife.tasks.grpc.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),                 // 5: com.dkhalife.tasks.grpc.DeleteTaskRequest
	(*CompleteTaskRequest)(nil),               // 6: com.dkhalife.tasks.grpc.CompleteTaskRequest
	(*UncompleteTaskRequest)(nil),             // 7: com.dkhalife.tasks.grpc.UncompleteTaskRequest
	(*SkipTaskRequest)(nil),                   // 8: com.dkhalife.tasks.grpc.SkipTaskRequest
	(*UpdateDueDateRequest)(nil),              // 9: com.dkhalife.tasks.grpc.UpdateDueDateRequest
	(*GetTaskHistoryRequest)(nil),             // 10: com.dkhalife.tasks.grpc.GetTaskHistoryRequest
	(*CreateLabelRequest)(nil),                // 11: com.dkhalife.tasks.grpc.CreateLabelRequest
	(*UpdateLabelRequest)(nil),                // 12: com.dkhalife.tasks.grpc.UpdateLabelRequest
	(*DeleteLabelRequest)(nil),                // 13: com.dkhalife.tasks.grpc.DeleteLabelRequest
	(*UpdateNotificationSettingsRequest)(nil), // 14: com.dkhalife.tasks.grpc.UpdateNotificationSettingsRequest
	(*ChangePasswordRequest)(nil),             // 15: com.dkhalife.tasks.grpc.ChangePasswordRequest
	(*CreateAppTokenRequest)(nil),             // 16: com.dkhalife.tasks.grpc.CreateAppTokenRequest
	(*DeleteAppTokenRequest)(nil),             // 17: com.dkhalife.tasks.grpc.DeleteAppTokenRequest
	(*SignUpRequest)(nil),                     // 18: com.dkhalife.tasks.grpc.SignUpRequest
	(*LoginRequest)(nil),                      // 19: com.dkhalife.tasks.grpc.LoginRequest
	(*RefreshTokenRequest)(nil),               // 20: com.dkhalife.tasks.grpc.RefreshTokenRequest
	(*ResetPasswordRequest)(nil),              // 21: com.dkhalife.tasks.grpc.ResetPasswordRequest
	(*UpdatePasswordRequest)(nil),             // 22: com.dkhalife.tasks.grpc.UpdatePasswordRequest
	(*TasksResponse)(nil),                     // 23: com.dkhalife.tasks.grpc.TasksResponse
	(*TaskResponse)(nil),                      // 24: com.dkhalife.tasks.grpc.TaskResponse
	(*TaskHistoryResponse)(nil),               // 25: com.dkhalife.tasks.grpc.TaskHistoryResponse
	(*LabelsResponse)(nil),                    // 26: com.dkhalife.tasks.grpc.LabelsResponse
	(*LabelResponse)(nil),                     // 27: com.dkhalife.tasks.grpc.LabelResponse
	(*UserProfileResponse)(nil),               // 28: com.dkhalife.tasks.grpc.UserProfileResponse
	(*AppTokensResponse)(nil),                 // 29: com.dkhalife.tasks.grpc.AppTokensResponse
	(*AppTokenResponse)(nil),                  // 30: com.dkhalife.tasks.grpc.AppTokenResponse
	(*AuthResponse)(nil),                      // 31: com.dkhalife.tasks.grpc.AuthResponse
}
var file_task_service_proto_depIdxs = []int32{
	0,  // 0: com.dkhalife.tasks.grpc.TaskService.GetTasks:input_type -> com.dkhalife.tasks.grpc.Empty
	1,  // 1: com.dkhalife.tasks.grpc.TaskService.GetCompletedTasks:input_type -> com.dkhalife.tasks.grpc.GetCompletedTasksRequest
	2,  // 2: com.dkhalife.tasks.grpc.TaskService.GetTask:input_type -> com.dkhalife.tasks.grpc.GetTaskRequest
	3,  // 3: com.dkhalife.tasks.grpc.TaskService.CreateTask:input_type -> com.dkhalife.tasks.grpc.CreateTaskRequest
	4,  // 4: com.dkhalife.tasks.grpc.TaskService.UpdateTask:input_type -> com.dkhalife.tasks.grpc.UpdateTaskRequest
	5,  // 5: com.dkhalife.tasks.grpc.TaskService.DeleteTask:input_type -> com.dkhalife.tasks.grpc.DeleteTaskRequest
	6,  // 6: com.dkhalife.tasks.grpc.TaskService.CompleteTask:input_type -> com.dkhalife.tasks.grpc.CompleteTaskRequest
	7,  // 7: com.dkhalife.tasks.grpc.TaskService.UncompleteTask:input_type -> com.dkhalife.tasks.grpc.UncompleteTaskRequest
	8,  // 8: com.dkhalife.tasks.grpc.TaskService.SkipTask:input_type -> com.dkhalife.tasks.grpc.SkipTaskRequest
	9,  // 9: com.dkhalife.tasks.grpc.TaskService.UpdateDueDate:input_type -> com.dkhalife.tasks.grpc.UpdateDueDateRequest
	10, // 10: com.dkhalife.tasks.grpc.TaskService.GetTaskHistory:input_type -> com.dkhalife.tasks.grpc.GetTaskHistoryRequest
	0,  // 11: com.dkhalife.tasks.grpc.LabelService.GetLabels:input_type -> com.dkhalife.tasks.grpc.Empty
	11, // 12: com.dkhalife.tasks.grpc.LabelService.CreateLabel:input_type -> com.dkhalife.tasks.grpc.CreateLabelRequest
	12, // 13: com.dkhalife.tasks.grpc.LabelService.UpdateLabel:input_type -> com.dkhalife.tasks.grpc.UpdateLabelRequest
	13, // 14: com.dkhalife.tasks.grpc.LabelService.DeleteLabel:input_type -> com.dkhalife.tasks.grpc.DeleteLabelRequest
	0,  // 15: com.dkhalife.tasks.grpc.UserService.GetProfile:input_type -> com.dkhalife.tasks.grpc.Empty
	14, // 16: com.dkhalife.tasks.grpc.UserService.UpdateNotificationSettings:input_type -> com.dkhalife.tasks.grpc.UpdateNotificationSettingsRequest
	15, // 17: com.dkhalife.tasks.grpc.UserService.ChangePassword:input_type -> com.dkhalife.tasks.grpc.ChangePasswordRequest
	0,  // 18: com.dkhalife.tasks.grpc.TokenService.GetAppTokens:input_type -> com.dkhalife.tasks.grpc.Empty
	16, // 19: com.dkhalife.tasks.grpc.TokenService.CreateAppToken:input_type -> com.dkhalife.tasks.grpc.CreateAppTokenRequest
	17, // 20: com.dkhalife.tasks.grpc.TokenService.DeleteAppToken:input_type -> com.dkhalife.tasks.grpc.DeleteAppTokenRequest
	18, // 21: com.dkhalife.tasks.grpc.AuthService.SignUp:input_type -> com.dkhalife.tasks.grpc.SignUpRequest
	19, // 22: com.dkhalife.tasks.grpc.AuthService.Login:input_type -> com.dkhalife.tasks.grpc.LoginRequest
	20, // 23: com.dkhalife.tasks.grpc.AuthService.RefreshToken:input_type -> com.dkhalife.tasks.grpc.RefreshTokenRequest
	21, // 24: com.dkhalife.tasks.grpc.AuthService.ResetPassword:input_type -> com.dkhalife.tasks.grpc.ResetPasswordRequest
	22, // 25: com.dkhalife.tasks.grpc.AuthService.UpdatePassword:input_type -> com.dkhalife.tasks.grpc.UpdatePasswordRequest
	23, // 26: com.dkhalife.tasks.grpc.TaskService.GetTasks:output_type -> com.dkhalife.tasks.grpc.TasksResponse
	23, // 27: com.dkhalife.tasks.grpc.TaskService.GetCompletedTasks:output_type -> com.dkhalife.tasks.grpc.TasksResponse
	24, // 28: com.dkhalife.tasks.grpc.TaskService.GetTask:output_type -> com.dkhalife.tasks.grpc.TaskResponse
	24, // 29: com.dkhalife.tasks.grpc.TaskService.CreateTask:output_type -> com.dkhalife.tasks.grpc.TaskResponse
	24, // 30: com.dkhalife.tasks.grpc.TaskService.UpdateTask:output_type -> com.dkhalife.tasks.grpc.TaskResponse
	0,  // 31: com.dkhalife.tasks.grpc.TaskService.DeleteTask:output_type -> com.dkhalife.tasks.grpc.Empty
	24, // 32: com.dkhalife.tasks.grpc.TaskService.CompleteTask:output_type -> com.dkhalife.tasks.grpc.TaskResponse
	24, // 33: com.dkhalife.tasks.grpc.TaskService.UncompleteTask:output_type -> com.dkhalife.tasks.grpc.TaskResponse
	24, // 34: com.dkhalife.tasks.grpc.TaskService.SkipTask:output_type -> com.dkhalife.tasks.grpc.TaskResponse
	24, // 35: com.dkhalife.tasks.grpc.TaskService.UpdateDueDate:output_type -> com.dkhalife.tasks.grpc.TaskResponse
	25, // 36: com.dkhalife.tasks.grpc.TaskService.GetTaskHistory:output_type -> com.dkhalife.tasks.grpc.TaskHistoryResponse
	26, // 37: com.dkhalife.tasks.grpc.LabelService.GetLabels:output_type -> com.dkhalife.tasks.grpc.LabelsResponse
	27, // 38: com.dkhalife.tasks.grpc.LabelService.CreateLabel:output_type -> com.dkhalife.tasks.grpc.LabelResponse
	27, // 39: com.dkhalife.tasks.grpc.LabelService.UpdateLabel:output_type -> com.dkhalife.tasks.grpc.LabelResponse
	0,  // 40: com.dkhalife.tasks.grpc.LabelService.DeleteLabel:output_type -> com.dkhalife.tasks.grpc.Empty
	28, // 41: com.dkhalife.tasks.grpc.UserService.GetProfile:output_type -> com.dkhalife.tasks.grpc.UserProfileResponse
	0,  // 42: com.dkhalife.tasks.grpc.UserService.UpdateNotificationSettings:output_type -> com.dkhalife.tasks.grpc.Empty
	0,  // 43: com.dkhalife.tasks.grpc.UserService.ChangePassword:output_type -> com.dkhalife.tasks.grpc.Empty
	29, // 44: com.dkhalife.tasks.grpc.TokenService.GetAppTokens:output_type -> com.dkhalife.tasks.grpc.AppTokensResponse
	30, // 45: com.dkhalife.tasks.grpc.TokenService.CreateAppToken:output_type -> com.dkhalife.tasks.grpc.AppTokenResponse
	0,  // 46: com.dkhalife.tasks.grpc.TokenService.DeleteAppToken:output_type -> com.dkhalife.tasks.grpc.Empty
	0,  // 47: com.dkhalife.tasks.grpc.AuthService.SignUp:output_type -> com.dkhalife.tasks.grpc.Empty
	31, // 48: com.dkhalife.tasks.grpc.AuthService.Login:output_type -> com.dkhalife.tasks.grpc.AuthResponse
	31, // 49: com.dkhalife.tasks.grpc.AuthService.RefreshToken:output_type -> com.dkhalife.tasks.grpc.AuthResponse
	0,  // 50: com.dkhalife.tasks.grpc.AuthService.ResetPassword:output_type -> com.dkhalife.tasks.grpc.Empty
	0,  // 51: com.dkhalife.tasks.grpc.AuthService.UpdatePassword:output_type -> com.dkhalife.tasks.grpc.Empty
	26, // [26:52] is the sub-list for method output_type
	0,  // [0:26] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_task_service_proto_init() }
func file_task_service_proto_init() {
	if File_task_service_proto != nil {
		return
	}
	file_common_proto_init()
	file_task_proto_init()
	file_label_proto_init()
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_service_proto_rawDesc), len(file_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_task_service_proto_goTypes,
		DependencyIndexes: file_task_service_proto_depIdxs,
	}.Build()
	File_task_service_proto = out.File
	file_task_service_proto_goTypes = nil
	file_task_service_proto_depIdxs = nil
}
