// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: task.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            int32                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	NextDueDate   *int64                      `protobuf:"varint,3,opt,name=next_due_date,json=nextDueDate,proto3,oneof" json:"next_due_date,omitempty"`
	EndDate       *int64                      `protobuf:"varint,4,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	IsRolling     bool                        `protobuf:"varint,5,opt,name=is_rolling,json=isRolling,proto3" json:"is_rolling,omitempty"`
	Frequency     *Frequency                  `protobuf:"bytes,6,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Notification  *NotificationTriggerOptions `protobuf:"bytes,7,opt,name=notification,proto3" json:"notification,omitempty"`
	Labels        []*Label                    `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetNextDueDate() int64 {
	if x != nil && x.NextDueDate != nil {
		return *x.NextDueDate
	}
	return 0
}

func (x *Task) GetEndDate() int64 {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return 0
}

func (x *Task) GetIsRolling() bool {
	if x != nil {
		return x.IsRolling
	}
	return false
}

func (x *Task) GetFrequency() *Frequency {
	if x != nil {
		return x.Frequency
	}
	return nil
}

func (x *Task) GetNotification() *NotificationTriggerOptions {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *Task) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TaskHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CompletedDate *int64                 `protobuf:"varint,3,opt,name=completed_date,json=completedDate,proto3,oneof" json:"completed_date,omitempty"`
	DueDate       *int64                 `protobuf:"varint,4,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskHistory) Reset() {
	*x = TaskHistory{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskHistory) ProtoMessage() {}

func (x *TaskHistory) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskHistory.ProtoReflect.Descriptor instead.
func (*TaskHistory) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskHistory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskHistory) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskHistory) GetCompletedDate() int64 {
	if x != nil && x.CompletedDate != nil {
		return *x.CompletedDate
	}
	return 0
}

func (x *TaskHistory) GetDueDate() int64 {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return 0
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Title         string                      `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	NextDueDate   *int64                      `protobuf:"varint,2,opt,name=next_due_date,json=nextDueDate,proto3,oneof" json:"next_due_date,omitempty"`
	EndDate       *int64                      `protobuf:"varint,3,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	IsRolling     bool                        `protobuf:"varint,4,opt,name=is_rolling,json=isRolling,proto3" json:"is_rolling,omitempty"`
	Frequency     *Frequency                  `protobuf:"bytes,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Notification  *NotificationTriggerOptions `protobuf:"bytes,6,opt,name=notification,proto3" json:"notification,omitempty"`
	LabelIds      []int32                     `protobuf:"varint,7,rep,packed,name=label_ids,json=labelIds,proto3" json:"label_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetNextDueDate() int64 {
	if x != nil && x.NextDueDate != nil {
		return *x.NextDueDate
	}
	return 0
}

func (x *CreateTaskRequest) GetEndDate() int64 {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return 0
}

func (x *CreateTaskRequest) GetIsRolling() bool {
	if x != nil {
		return x.IsRolling
	}
	return false
}

func (x *CreateTaskRequest) GetFrequency() *Frequency {
	if x != nil {
		return x.Frequency
	}
	return nil
}

func (x *CreateTaskRequest) GetNotification() *NotificationTriggerOptions {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *CreateTaskRequest) GetLabelIds() []int32 {
	if x != nil {
		return x.LabelIds
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            int32                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	NextDueDate   *int64                      `protobuf:"varint,3,opt,name=next_due_date,json=nextDueDate,proto3,oneof" json:"next_due_date,omitempty"`
	EndDate       *int64                      `protobuf:"varint,4,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	IsRolling     bool                        `protobuf:"varint,5,opt,name=is_rolling,json=isRolling,proto3" json:"is_rolling,omitempty"`
	Frequency     *Frequency                  `protobuf:"bytes,6,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Notification  *NotificationTriggerOptions `protobuf:"bytes,7,opt,name=notification,proto3" json:"notification,omitempty"`
	LabelIds      []int32                     `protobuf:"varint,8,rep,packed,name=label_ids,json=labelIds,proto3" json:"label_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetNextDueDate() int64 {
	if x != nil && x.NextDueDate != nil {
		return *x.NextDueDate
	}
	return 0
}

func (x *UpdateTaskRequest) GetEndDate() int64 {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return 0
}

func (x *UpdateTaskRequest) GetIsRolling() bool {
	if x != nil {
		return x.IsRolling
	}
	return false
}

func (x *UpdateTaskRequest) GetFrequency() *Frequency {
	if x != nil {
		return x.Frequency
	}
	return nil
}

func (x *UpdateTaskRequest) GetNotification() *NotificationTriggerOptions {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *UpdateTaskRequest) GetLabelIds() []int32 {
	if x != nil {
		return x.LabelIds
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EndRecurrence bool                   `protobuf:"varint,2,opt,name=end_recurrence,json=endRecurrence,proto3" json:"end_recurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompleteTaskRequest) GetEndRecurrence() bool {
	if x != nil {
		return x.EndRecurrence
	}
	return false
}

type UncompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncompleteTaskRequest) Reset() {
	*x = UncompleteTaskRequest{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncompleteTaskRequest) ProtoMessage() {}

func (x *UncompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*UncompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *UncompleteTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SkipTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipTaskRequest) Reset() {
	*x = SkipTaskRequest{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipTaskRequest) ProtoMessage() {}

func (x *SkipTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipTaskRequest.ProtoReflect.Descriptor instead.
func (*SkipTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

func (x *SkipTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateDueDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DueDate       int64                  `protobuf:"varint,2,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDueDateRequest) Reset() {
	*x = UpdateDueDateRequest{}
	mi := &file_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDueDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDueDateRequest) ProtoMessage() {}

func (x *UpdateDueDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDueDateRequest.ProtoReflect.Descriptor instead.
func (*UpdateDueDateRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDueDateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDueDateRequest) GetDueDate() int64 {
	if x != nil {
		return x.DueDate
	}
	return 0
}

type GetTaskHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskHistoryRequest) Reset() {
	*x = GetTaskHistoryRequest{}
	mi := &file_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskHistoryRequest) ProtoMessage() {}

func (x *GetTaskHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTaskHistoryRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskHistoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCompletedTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletedTasksRequest) Reset() {
	*x = GetCompletedTasksRequest{}
	mi := &file_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletedTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletedTasksRequest) ProtoMessage() {}

func (x *GetCompletedTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletedTasksRequest.ProtoReflect.Descriptor instead.
func (*GetCompletedTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{11}
}

func (x *GetCompletedTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCompletedTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{12}
}

func (x *TaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type TasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksResponse) Reset() {
	*x = TasksResponse{}
	mi := &file_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksResponse) ProtoMessage() {}

func (x *TasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksResponse.ProtoReflect.Descriptor instead.
func (*TasksResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{13}
}

func (x *TasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*TaskHistory         `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskHistoryResponse) Reset() {
	*x = TaskHistoryResponse{}
	mi := &file_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskHistoryResponse) ProtoMessage() {}

func (x *TaskHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskHistoryResponse.ProtoReflect.Descriptor instead.
func (*TaskHistoryResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{14}
}

func (x *TaskHistoryResponse) GetHistory() []*TaskHistory {
	if x != nil {
		return x.History
	}
	return nil
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x17com.dkhalife.tasks.grpc\x1a\fcommon.proto\x1a\vlabel.proto\"\x86\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12'\n" +
	"\rnext_due_date\x18\x03 \x01(\x03H\x00R\vnextDueDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x04 \x01(\x03H\x01R\aendDate\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_rolling\x18\x05 \x01(\bR\tisRolling\x12@\n" +
	"\tfrequency\x18\x06 \x01(\v2\".com.dkhalife.tasks.grpc.FrequencyR\tfrequency\x12W\n" +
	"\fnotification\x18\a \x01(\v23.com.dkhalife.tasks.grpc.NotificationTriggerOptionsR\fnotification\x126\n" +
	"\x06labels\x18\b \x03(\v2\x1e.com.dkhalife.tasks.grpc.LabelR\x06labelsB\x10\n" +
	"\x0e_next_due_dateB\v\n" +
	"\t_end_date\"\xa2\x01\n" +
	"\vTaskHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\x12*\n" +
	"\x0ecompleted_date\x18\x03 \x01(\x03H\x00R\rcompletedDate\x88\x01\x01\x12\x1e\n" +
	"\bdue_date\x18\x04 \x01(\x03H\x01R\adueDate\x88\x01\x01B\x11\n" +
	"\x0f_completed_dateB\v\n" +
	"\t_due_date\"\xe8\x02\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12'\n" +
	"\rnext_due_date\x18\x02 \x01(\x03H\x00R\vnextDueDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x03 \x01(\x03H\x01R\aendDate\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_rolling\x18\x04 \x01(\bR\tisRolling\x12@\n" +
	"\tfrequency\x18\x05 \x01(\v2\".com.dkhalife.tasks.grpc.FrequencyR\tfrequency\x12W\n" +
	"\fnotification\x18\x06 \x01(\v23.com.dkhalife.tasks.grpc.NotificationTriggerOptionsR\fnotification\x12\x1b\n" +
	"\tlabel_ids\x18\a \x03(\x05R\blabelIdsB\x10\n" +
	"\x0e_next_due_dateB\v\n" +
	"\t_end_date\"\xf8\x02\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12'\n" +
	"\rnext_due_date\x18\x03 \x01(\x03H\x00R\vnextDueDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x04 \x01(\x03H\x01R\aendDate\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_rolling\x18\x05 \x01(\bR\tisRolling\x12@\n" +
	"\tfrequency\x18\x06 \x01(\v2\".com.dkhalife.tasks.grpc.FrequencyR\tfrequency\x12W\n" +
	"\fnotification\x18\a \x01(\v23.com.dkhalife.tasks.grpc.NotificationTriggerOptionsR\fnotification\x12\x1b\n" +
	"\tlabel_ids\x18\b \x03(\x05R\blabelIdsB\x10\n" +
	"\x0e_next_due_dateB\v\n" +
	"\t_end_date\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"L\n" +
	"\x13CompleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\x0eend_recurrence\x18\x02 \x01(\bR\rendRecurrence\"'\n" +
	"\x15UncompleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"!\n" +
	"\x0fSkipTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"A\n" +
	"\x14UpdateDueDateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bdue_date\x18\x02 \x01(\x03R\adueDate\"'\n" +
	"\x15GetTaskHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"D\n" +
	"\x18GetCompletedTasksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"A\n" +
	"\fTaskResponse\x121\n" +
	"\x04task\x18\x01 \x01(\v2\x1d.com.dkhalife.tasks.grpc.TaskR\x04task\"D\n" +
	"\rTasksResponse\x123\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1d.com.dkhalife.tasks.grpc.TaskR\x05tasks\"U\n" +
	"\x13TaskHistoryResponse\x12>\n" +
	"\ahistory\x18\x01 \x03(\v2$.com.dkhalife.tasks.grpc.TaskHistoryR\ahistoryBR\n" +
	"\x17com.dkhalife.tasks.grpcB\tTaskProtoZ,github.com/dkhalife/task-wizard/servers/grpcb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_task_proto_goTypes = []any{
	(*Task)(nil),                       // 0: com.dkhalife.tasks.grpc.Task
	(*TaskHistory)(nil),                // 1: com.dkhalife.tasks.grpc.TaskHistory
	(*CreateTaskRequest)(nil),          // 2: com.dkhalife.tasks.grpc.CreateTaskRequest
	(*UpdateTaskRequest)(nil),          // 3: com.dkhalife.tasks.grpc.UpdateTaskRequest
	(*GetTaskRequest)(nil),             // 4: com.dkhalife.tasks.grpc.GetTaskRequest
	(*DeleteTaskRequest)(nil),          // 5: com.dkhalife.tasks.grpc.DeleteTaskRequest
	(*CompleteTaskRequest)(nil),        // 6: com.dkhalife.tasks.grpc.CompleteTaskRequest
	(*UncompleteTaskRequest)(nil),      // 7: com.dkhalife.tasks.grpc.UncompleteTaskRequest
	(*SkipTaskRequest)(nil),            // 8: com.dkhalife.tasks.grpc.SkipTaskRequest
	(*UpdateDueDateRequest)(nil),       // 9: com.dkhalife.tasks.grpc.UpdateDueDateRequest
	(*GetTaskHistoryRequest)(nil),      // 10: com.dkhalife.tasks.grpc.GetTaskHistoryRequest
	(*GetCompletedTasksRequest)(nil),   // 11: com.dkhalife.tasks.grpc.GetCompletedTasksRequest
	(*TaskResponse)(nil),               // 12: com.dkhalife.tasks.grpc.TaskResponse
	(*TasksResponse)(nil),              // 13: com.dkhalife.tasks.grpc.TasksResponse
	(*TaskHistoryResponse)(nil),        // 14: com.dkhalife.tasks.grpc.TaskHistoryResponse
	(*Frequency)(nil),                  // 15: com.dkhalife.tasks.grpc.Frequency
	(*NotificationTriggerOptions)(nil), // 16: com.dkhalife.tasks.grpc.NotificationTriggerOptions
	(*Label)(nil),                      // 17: com.dkhalife.tasks.grpc.Label
}
var file_task_proto_depIdxs = []int32{
	15, // 0: com.dkhalife.tasks.grpc.Task.frequency:type_name -> com.dkhalife.tasks.grpc.Frequency
	16, // 1: com.dkhalife.tasks.grpc.Task.notification:type_name -> com.dkhalife.tasks.grpc.NotificationTriggerOptions
	17, // 2: com.dkhalife.tasks.grpc.Task.labels:type_name -> com.dkhalife.tasks.grpc.Label
	15, // 3: com.dkhalife.tasks.grpc.CreateTaskRequest.frequency:type_name -> com.dkhalife.tasks.grpc.Frequency
	16, // 4: com.dkhalife.tasks.grpc.CreateTaskRequest.notification:type_name -> com.dkhalife.tasks.grpc.NotificationTriggerOptions
	15, // 5: com.dkhalife.tasks.grpc.UpdateTaskRequest.frequency:type_name -> com.dkhalife.tasks.grpc.Frequency
	16, // 6: com.dkhalife.tasks.grpc.UpdateTaskRequest.notification:type_name -> com.dkhalife.tasks.grpc.NotificationTriggerOptions
	0,  // 7: com.dkhalife.tasks.grpc.TaskResponse.task:type_name -> com.dkhalife.tasks.grpc.Task
	0,  // 8: com.dkhalife.tasks.grpc.TasksResponse.tasks:type_name -> com.dkhalife.tasks.grpc.Task
	1,  // 9: com.dkhalife.tasks.grpc.TaskHistoryResponse.history:type_name -> com.dkhalife.tasks.grpc.TaskHistory
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_common_proto_init()
	file_label_proto_init()
	file_task_proto_msgTypes[0].OneofWrappers = []any{}
	file_task_proto_msgTypes[1].OneofWrappers = []any{}
	file_task_proto_msgTypes[2].OneofWrappers = []any{}
	file_task_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
