services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-wizard
    restart: unless-stopped
    volumes:
    - ./data:/usr/src/app/data
    ports:
    - "8085:8000"
    hostname: task-wizard
