package caldav

import (
	"bufio"
	"strings"
	"time"
)

// ParseVTODO extracts the summary and due date from a VTODO iCalendar item.
// It only supports very simple VTODO documents generated by this app.
func ParseVTODO(data string) (title string, due *time.Time, err error) {
	scanner := bufio.NewScanner(strings.NewReader(data))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "SUMMARY") {
			if idx := strings.Index(line, ":"); idx != -1 {
				title = strings.TrimSpace(line[idx+1:])
			}
		}
		if strings.HasPrefix(line, "DUE") {
			if idx := strings.Index(line, ":"); idx != -1 {
				ts := strings.TrimSpace(line[idx+1:])
				if t, err2 := time.Parse("20060102T150405Z", ts); err2 == nil {
					tt := t.UTC()
					due = &tt
				} else if t, err3 := time.Parse("20060102", ts); err3 == nil {
					tt := t.UTC()
					due = &tt
				}
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return "", nil, err
	}
	return title, due, nil
}
