package com.dkhalife.tasks.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val PrimaryLight = Color(0xFF1A6B52)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFA8F2D3)
val OnPrimaryContainerLight = Color(0xFF002117)
val SecondaryLight = Color(0xFF4B635A)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCEE9DC)
val OnSecondaryContainerLight = Color(0xFF072019)
val TertiaryLight = Color(0xFF406376)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC3E8FE)
val OnTertiaryContainerLight = Color(0xFF001E2C)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF5FBF6)
val OnBackgroundLight = Color(0xFF171D1A)
val SurfaceLight = Color(0xFFF5FBF6)
val OnSurfaceLight = Color(0xFF171D1A)
val SurfaceVariantLight = Color(0xFFDBE5DE)
val OnSurfaceVariantLight = Color(0xFF404944)
val OutlineLight = Color(0xFF707973)
val OutlineVariantLight = Color(0xFFBFC9C2)
val SurfaceTintLight = PrimaryLight

// Dark scheme
val PrimaryDark = Color(0xFF8CD5B8)
val OnPrimaryDark = Color(0xFF00382A)
val PrimaryContainerDark = Color(0xFF00513D)
val OnPrimaryContainerDark = Color(0xFFA8F2D3)
val SecondaryDark = Color(0xFFB2CCC0)
val OnSecondaryDark = Color(0xFF1E352D)
val SecondaryContainerDark = Color(0xFF344C43)
val OnSecondaryContainerDark = Color(0xFFCEE9DC)
val TertiaryDark = Color(0xFFA7CCE1)
val OnTertiaryDark = Color(0xFF0B3446)
val TertiaryContainerDark = Color(0xFF274B5E)
val OnTertiaryContainerDark = Color(0xFFC3E8FE)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF0F1512)
val OnBackgroundDark = Color(0xFFDFE4DF)
val SurfaceDark = Color(0xFF0F1512)
val OnSurfaceDark = Color(0xFFDFE4DF)
val SurfaceVariantDark = Color(0xFF404944)
val OnSurfaceVariantDark = Color(0xFFBFC9C2)
val OutlineDark = Color(0xFF8A938D)
val OutlineVariantDark = Color(0xFF404944)
val SurfaceTintDark = PrimaryDark
