database:
  migration: true
  path: /config/task-wizard.db
jwt:
  secret: "secret"
  session_time: 168h
  max_refresh: 168h
server:
  host_name: example.com
  port: 2021
  read_timeout: 2s
  write_timeout: 1s
  rate_period: 60s
  rate_limit: 300
  serve_frontend: true
  registration: true
  log_level: "warn"
  allowed_origins:
    - "https://example.com"
scheduler_jobs:
  due_frequency: 5m
  overdue_frequency: 24h
  password_reset_validity: 24h
  token_expiration_reminder: 72h
  notification_cleanup: 10m
  token_expiration_cleanup: 24h
email:
  host: 
  port: 
  email:  
  password:
