name: "local"
database:
  migration: true
  path: task-wizard.db
jwt:
  secret: "secret"
  session_time: 168h
  max_refresh: 168h
server:
  host_name: localhost
  port: 2021
  read_timeout: 2s
  write_timeout: 1s
  rate_period: 60s
  rate_limit: 300
  serve_frontend: false
  registration: true
  debug: true
scheduler_jobs:
  due_frequency: 1m
  overdue_frequency: 1m
  password_reset_validity: 1m
  token_expiration_reminder: 1m
email:
  host: 
  port: 
  email:  
  password:
