// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: task.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Frequency, NotificationTriggerOptions } from "./common";
import { Label } from "./label";

export interface Task {
  id: number;
  title: string;
  nextDueDate?: number | undefined;
  endDate?: number | undefined;
  isRolling: boolean;
  frequency: Frequency | undefined;
  notification: NotificationTriggerOptions | undefined;
  labels: Label[];
}

export interface TaskHistory {
  id: number;
  taskId: number;
  completedDate?: number | undefined;
  dueDate?: number | undefined;
}

export interface CreateTaskRequest {
  title: string;
  nextDueDate?: number | undefined;
  endDate?: number | undefined;
  isRolling: boolean;
  frequency: Frequency | undefined;
  notification: NotificationTriggerOptions | undefined;
  labelIds: number[];
}

export interface UpdateTaskRequest {
  id: number;
  title: string;
  nextDueDate?: number | undefined;
  endDate?: number | undefined;
  isRolling: boolean;
  frequency: Frequency | undefined;
  notification: NotificationTriggerOptions | undefined;
  labelIds: number[];
}

export interface GetTaskRequest {
  id: number;
}

export interface DeleteTaskRequest {
  id: number;
}

export interface CompleteTaskRequest {
  id: number;
  endRecurrence: boolean;
}

export interface UncompleteTaskRequest {
  id: number;
}

export interface SkipTaskRequest {
  id: number;
}

export interface UpdateDueDateRequest {
  id: number;
  dueDate: number;
}

export interface GetTaskHistoryRequest {
  id: number;
}

export interface GetCompletedTasksRequest {
  limit: number;
  page: number;
}

export interface TaskResponse {
  task: Task | undefined;
}

export interface TasksResponse {
  tasks: Task[];
}

export interface TaskHistoryResponse {
  history: TaskHistory[];
}

function createBaseTask(): Task {
  return {
    id: 0,
    title: "",
    nextDueDate: undefined,
    endDate: undefined,
    isRolling: false,
    frequency: undefined,
    notification: undefined,
    labels: [],
  };
}

export const Task: MessageFns<Task> = {
  encode(message: Task, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.nextDueDate !== undefined) {
      writer.uint32(24).int64(message.nextDueDate);
    }
    if (message.endDate !== undefined) {
      writer.uint32(32).int64(message.endDate);
    }
    if (message.isRolling !== false) {
      writer.uint32(40).bool(message.isRolling);
    }
    if (message.frequency !== undefined) {
      Frequency.encode(message.frequency, writer.uint32(50).fork()).join();
    }
    if (message.notification !== undefined) {
      NotificationTriggerOptions.encode(message.notification, writer.uint32(58).fork()).join();
    }
    for (const v of message.labels) {
      Label.encode(v!, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Task {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTask();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.nextDueDate = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.endDate = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isRolling = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.frequency = Frequency.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.notification = NotificationTriggerOptions.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.labels.push(Label.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Task {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      nextDueDate: isSet(object.nextDueDate) ? globalThis.Number(object.nextDueDate) : undefined,
      endDate: isSet(object.endDate) ? globalThis.Number(object.endDate) : undefined,
      isRolling: isSet(object.isRolling) ? globalThis.Boolean(object.isRolling) : false,
      frequency: isSet(object.frequency) ? Frequency.fromJSON(object.frequency) : undefined,
      notification: isSet(object.notification) ? NotificationTriggerOptions.fromJSON(object.notification) : undefined,
      labels: globalThis.Array.isArray(object?.labels) ? object.labels.map((e: any) => Label.fromJSON(e)) : [],
    };
  },

  toJSON(message: Task): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.nextDueDate !== undefined) {
      obj.nextDueDate = Math.round(message.nextDueDate);
    }
    if (message.endDate !== undefined) {
      obj.endDate = Math.round(message.endDate);
    }
    if (message.isRolling !== false) {
      obj.isRolling = message.isRolling;
    }
    if (message.frequency !== undefined) {
      obj.frequency = Frequency.toJSON(message.frequency);
    }
    if (message.notification !== undefined) {
      obj.notification = NotificationTriggerOptions.toJSON(message.notification);
    }
    if (message.labels?.length) {
      obj.labels = message.labels.map((e) => Label.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Task>): Task {
    return Task.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Task>): Task {
    const message = createBaseTask();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.nextDueDate = object.nextDueDate ?? undefined;
    message.endDate = object.endDate ?? undefined;
    message.isRolling = object.isRolling ?? false;
    message.frequency = (object.frequency !== undefined && object.frequency !== null)
      ? Frequency.fromPartial(object.frequency)
      : undefined;
    message.notification = (object.notification !== undefined && object.notification !== null)
      ? NotificationTriggerOptions.fromPartial(object.notification)
      : undefined;
    message.labels = object.labels?.map((e) => Label.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTaskHistory(): TaskHistory {
  return { id: 0, taskId: 0, completedDate: undefined, dueDate: undefined };
}

export const TaskHistory: MessageFns<TaskHistory> = {
  encode(message: TaskHistory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.taskId !== 0) {
      writer.uint32(16).int32(message.taskId);
    }
    if (message.completedDate !== undefined) {
      writer.uint32(24).int64(message.completedDate);
    }
    if (message.dueDate !== undefined) {
      writer.uint32(32).int64(message.dueDate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskHistory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskHistory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.taskId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.completedDate = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.dueDate = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskHistory {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      taskId: isSet(object.taskId) ? globalThis.Number(object.taskId) : 0,
      completedDate: isSet(object.completedDate) ? globalThis.Number(object.completedDate) : undefined,
      dueDate: isSet(object.dueDate) ? globalThis.Number(object.dueDate) : undefined,
    };
  },

  toJSON(message: TaskHistory): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.taskId !== 0) {
      obj.taskId = Math.round(message.taskId);
    }
    if (message.completedDate !== undefined) {
      obj.completedDate = Math.round(message.completedDate);
    }
    if (message.dueDate !== undefined) {
      obj.dueDate = Math.round(message.dueDate);
    }
    return obj;
  },

  create(base?: DeepPartial<TaskHistory>): TaskHistory {
    return TaskHistory.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TaskHistory>): TaskHistory {
    const message = createBaseTaskHistory();
    message.id = object.id ?? 0;
    message.taskId = object.taskId ?? 0;
    message.completedDate = object.completedDate ?? undefined;
    message.dueDate = object.dueDate ?? undefined;
    return message;
  },
};

function createBaseCreateTaskRequest(): CreateTaskRequest {
  return {
    title: "",
    nextDueDate: undefined,
    endDate: undefined,
    isRolling: false,
    frequency: undefined,
    notification: undefined,
    labelIds: [],
  };
}

export const CreateTaskRequest: MessageFns<CreateTaskRequest> = {
  encode(message: CreateTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.nextDueDate !== undefined) {
      writer.uint32(16).int64(message.nextDueDate);
    }
    if (message.endDate !== undefined) {
      writer.uint32(24).int64(message.endDate);
    }
    if (message.isRolling !== false) {
      writer.uint32(32).bool(message.isRolling);
    }
    if (message.frequency !== undefined) {
      Frequency.encode(message.frequency, writer.uint32(42).fork()).join();
    }
    if (message.notification !== undefined) {
      NotificationTriggerOptions.encode(message.notification, writer.uint32(50).fork()).join();
    }
    writer.uint32(58).fork();
    for (const v of message.labelIds) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.nextDueDate = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.endDate = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isRolling = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.frequency = Frequency.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.notification = NotificationTriggerOptions.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag === 56) {
            message.labelIds.push(reader.int32());

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.labelIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTaskRequest {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      nextDueDate: isSet(object.nextDueDate) ? globalThis.Number(object.nextDueDate) : undefined,
      endDate: isSet(object.endDate) ? globalThis.Number(object.endDate) : undefined,
      isRolling: isSet(object.isRolling) ? globalThis.Boolean(object.isRolling) : false,
      frequency: isSet(object.frequency) ? Frequency.fromJSON(object.frequency) : undefined,
      notification: isSet(object.notification) ? NotificationTriggerOptions.fromJSON(object.notification) : undefined,
      labelIds: globalThis.Array.isArray(object?.labelIds) ? object.labelIds.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: CreateTaskRequest): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.nextDueDate !== undefined) {
      obj.nextDueDate = Math.round(message.nextDueDate);
    }
    if (message.endDate !== undefined) {
      obj.endDate = Math.round(message.endDate);
    }
    if (message.isRolling !== false) {
      obj.isRolling = message.isRolling;
    }
    if (message.frequency !== undefined) {
      obj.frequency = Frequency.toJSON(message.frequency);
    }
    if (message.notification !== undefined) {
      obj.notification = NotificationTriggerOptions.toJSON(message.notification);
    }
    if (message.labelIds?.length) {
      obj.labelIds = message.labelIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create(base?: DeepPartial<CreateTaskRequest>): CreateTaskRequest {
    return CreateTaskRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateTaskRequest>): CreateTaskRequest {
    const message = createBaseCreateTaskRequest();
    message.title = object.title ?? "";
    message.nextDueDate = object.nextDueDate ?? undefined;
    message.endDate = object.endDate ?? undefined;
    message.isRolling = object.isRolling ?? false;
    message.frequency = (object.frequency !== undefined && object.frequency !== null)
      ? Frequency.fromPartial(object.frequency)
      : undefined;
    message.notification = (object.notification !== undefined && object.notification !== null)
      ? NotificationTriggerOptions.fromPartial(object.notification)
      : undefined;
    message.labelIds = object.labelIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseUpdateTaskRequest(): UpdateTaskRequest {
  return {
    id: 0,
    title: "",
    nextDueDate: undefined,
    endDate: undefined,
    isRolling: false,
    frequency: undefined,
    notification: undefined,
    labelIds: [],
  };
}

export const UpdateTaskRequest: MessageFns<UpdateTaskRequest> = {
  encode(message: UpdateTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.nextDueDate !== undefined) {
      writer.uint32(24).int64(message.nextDueDate);
    }
    if (message.endDate !== undefined) {
      writer.uint32(32).int64(message.endDate);
    }
    if (message.isRolling !== false) {
      writer.uint32(40).bool(message.isRolling);
    }
    if (message.frequency !== undefined) {
      Frequency.encode(message.frequency, writer.uint32(50).fork()).join();
    }
    if (message.notification !== undefined) {
      NotificationTriggerOptions.encode(message.notification, writer.uint32(58).fork()).join();
    }
    writer.uint32(66).fork();
    for (const v of message.labelIds) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.nextDueDate = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.endDate = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isRolling = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.frequency = Frequency.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.notification = NotificationTriggerOptions.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag === 64) {
            message.labelIds.push(reader.int32());

            continue;
          }

          if (tag === 66) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.labelIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTaskRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      nextDueDate: isSet(object.nextDueDate) ? globalThis.Number(object.nextDueDate) : undefined,
      endDate: isSet(object.endDate) ? globalThis.Number(object.endDate) : undefined,
      isRolling: isSet(object.isRolling) ? globalThis.Boolean(object.isRolling) : false,
      frequency: isSet(object.frequency) ? Frequency.fromJSON(object.frequency) : undefined,
      notification: isSet(object.notification) ? NotificationTriggerOptions.fromJSON(object.notification) : undefined,
      labelIds: globalThis.Array.isArray(object?.labelIds) ? object.labelIds.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: UpdateTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.nextDueDate !== undefined) {
      obj.nextDueDate = Math.round(message.nextDueDate);
    }
    if (message.endDate !== undefined) {
      obj.endDate = Math.round(message.endDate);
    }
    if (message.isRolling !== false) {
      obj.isRolling = message.isRolling;
    }
    if (message.frequency !== undefined) {
      obj.frequency = Frequency.toJSON(message.frequency);
    }
    if (message.notification !== undefined) {
      obj.notification = NotificationTriggerOptions.toJSON(message.notification);
    }
    if (message.labelIds?.length) {
      obj.labelIds = message.labelIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateTaskRequest>): UpdateTaskRequest {
    return UpdateTaskRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateTaskRequest>): UpdateTaskRequest {
    const message = createBaseUpdateTaskRequest();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.nextDueDate = object.nextDueDate ?? undefined;
    message.endDate = object.endDate ?? undefined;
    message.isRolling = object.isRolling ?? false;
    message.frequency = (object.frequency !== undefined && object.frequency !== null)
      ? Frequency.fromPartial(object.frequency)
      : undefined;
    message.notification = (object.notification !== undefined && object.notification !== null)
      ? NotificationTriggerOptions.fromPartial(object.notification)
      : undefined;
    message.labelIds = object.labelIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetTaskRequest(): GetTaskRequest {
  return { id: 0 };
}

export const GetTaskRequest: MessageFns<GetTaskRequest> = {
  encode(message: GetTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTaskRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: GetTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create(base?: DeepPartial<GetTaskRequest>): GetTaskRequest {
    return GetTaskRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetTaskRequest>): GetTaskRequest {
    const message = createBaseGetTaskRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseDeleteTaskRequest(): DeleteTaskRequest {
  return { id: 0 };
}

export const DeleteTaskRequest: MessageFns<DeleteTaskRequest> = {
  encode(message: DeleteTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTaskRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: DeleteTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteTaskRequest>): DeleteTaskRequest {
    return DeleteTaskRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteTaskRequest>): DeleteTaskRequest {
    const message = createBaseDeleteTaskRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseCompleteTaskRequest(): CompleteTaskRequest {
  return { id: 0, endRecurrence: false };
}

export const CompleteTaskRequest: MessageFns<CompleteTaskRequest> = {
  encode(message: CompleteTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.endRecurrence !== false) {
      writer.uint32(16).bool(message.endRecurrence);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.endRecurrence = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CompleteTaskRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      endRecurrence: isSet(object.endRecurrence) ? globalThis.Boolean(object.endRecurrence) : false,
    };
  },

  toJSON(message: CompleteTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.endRecurrence !== false) {
      obj.endRecurrence = message.endRecurrence;
    }
    return obj;
  },

  create(base?: DeepPartial<CompleteTaskRequest>): CompleteTaskRequest {
    return CompleteTaskRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CompleteTaskRequest>): CompleteTaskRequest {
    const message = createBaseCompleteTaskRequest();
    message.id = object.id ?? 0;
    message.endRecurrence = object.endRecurrence ?? false;
    return message;
  },
};

function createBaseUncompleteTaskRequest(): UncompleteTaskRequest {
  return { id: 0 };
}

export const UncompleteTaskRequest: MessageFns<UncompleteTaskRequest> = {
  encode(message: UncompleteTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UncompleteTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUncompleteTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UncompleteTaskRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: UncompleteTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create(base?: DeepPartial<UncompleteTaskRequest>): UncompleteTaskRequest {
    return UncompleteTaskRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UncompleteTaskRequest>): UncompleteTaskRequest {
    const message = createBaseUncompleteTaskRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseSkipTaskRequest(): SkipTaskRequest {
  return { id: 0 };
}

export const SkipTaskRequest: MessageFns<SkipTaskRequest> = {
  encode(message: SkipTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SkipTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSkipTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SkipTaskRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: SkipTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create(base?: DeepPartial<SkipTaskRequest>): SkipTaskRequest {
    return SkipTaskRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SkipTaskRequest>): SkipTaskRequest {
    const message = createBaseSkipTaskRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseUpdateDueDateRequest(): UpdateDueDateRequest {
  return { id: 0, dueDate: 0 };
}

export const UpdateDueDateRequest: MessageFns<UpdateDueDateRequest> = {
  encode(message: UpdateDueDateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.dueDate !== 0) {
      writer.uint32(16).int64(message.dueDate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateDueDateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateDueDateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dueDate = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateDueDateRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      dueDate: isSet(object.dueDate) ? globalThis.Number(object.dueDate) : 0,
    };
  },

  toJSON(message: UpdateDueDateRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.dueDate !== 0) {
      obj.dueDate = Math.round(message.dueDate);
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateDueDateRequest>): UpdateDueDateRequest {
    return UpdateDueDateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateDueDateRequest>): UpdateDueDateRequest {
    const message = createBaseUpdateDueDateRequest();
    message.id = object.id ?? 0;
    message.dueDate = object.dueDate ?? 0;
    return message;
  },
};

function createBaseGetTaskHistoryRequest(): GetTaskHistoryRequest {
  return { id: 0 };
}

export const GetTaskHistoryRequest: MessageFns<GetTaskHistoryRequest> = {
  encode(message: GetTaskHistoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTaskHistoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTaskHistoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTaskHistoryRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: GetTaskHistoryRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create(base?: DeepPartial<GetTaskHistoryRequest>): GetTaskHistoryRequest {
    return GetTaskHistoryRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetTaskHistoryRequest>): GetTaskHistoryRequest {
    const message = createBaseGetTaskHistoryRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseGetCompletedTasksRequest(): GetCompletedTasksRequest {
  return { limit: 0, page: 0 };
}

export const GetCompletedTasksRequest: MessageFns<GetCompletedTasksRequest> = {
  encode(message: GetCompletedTasksRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.limit !== 0) {
      writer.uint32(8).int32(message.limit);
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCompletedTasksRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCompletedTasksRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCompletedTasksRequest {
    return {
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
    };
  },

  toJSON(message: GetCompletedTasksRequest): unknown {
    const obj: any = {};
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    return obj;
  },

  create(base?: DeepPartial<GetCompletedTasksRequest>): GetCompletedTasksRequest {
    return GetCompletedTasksRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetCompletedTasksRequest>): GetCompletedTasksRequest {
    const message = createBaseGetCompletedTasksRequest();
    message.limit = object.limit ?? 0;
    message.page = object.page ?? 0;
    return message;
  },
};

function createBaseTaskResponse(): TaskResponse {
  return { task: undefined };
}

export const TaskResponse: MessageFns<TaskResponse> = {
  encode(message: TaskResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.task !== undefined) {
      Task.encode(message.task, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.task = Task.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskResponse {
    return { task: isSet(object.task) ? Task.fromJSON(object.task) : undefined };
  },

  toJSON(message: TaskResponse): unknown {
    const obj: any = {};
    if (message.task !== undefined) {
      obj.task = Task.toJSON(message.task);
    }
    return obj;
  },

  create(base?: DeepPartial<TaskResponse>): TaskResponse {
    return TaskResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TaskResponse>): TaskResponse {
    const message = createBaseTaskResponse();
    message.task = (object.task !== undefined && object.task !== null) ? Task.fromPartial(object.task) : undefined;
    return message;
  },
};

function createBaseTasksResponse(): TasksResponse {
  return { tasks: [] };
}

export const TasksResponse: MessageFns<TasksResponse> = {
  encode(message: TasksResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tasks) {
      Task.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TasksResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTasksResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tasks.push(Task.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TasksResponse {
    return { tasks: globalThis.Array.isArray(object?.tasks) ? object.tasks.map((e: any) => Task.fromJSON(e)) : [] };
  },

  toJSON(message: TasksResponse): unknown {
    const obj: any = {};
    if (message.tasks?.length) {
      obj.tasks = message.tasks.map((e) => Task.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<TasksResponse>): TasksResponse {
    return TasksResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TasksResponse>): TasksResponse {
    const message = createBaseTasksResponse();
    message.tasks = object.tasks?.map((e) => Task.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTaskHistoryResponse(): TaskHistoryResponse {
  return { history: [] };
}

export const TaskHistoryResponse: MessageFns<TaskHistoryResponse> = {
  encode(message: TaskHistoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.history) {
      TaskHistory.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskHistoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskHistoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.history.push(TaskHistory.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskHistoryResponse {
    return {
      history: globalThis.Array.isArray(object?.history) ? object.history.map((e: any) => TaskHistory.fromJSON(e)) : [],
    };
  },

  toJSON(message: TaskHistoryResponse): unknown {
    const obj: any = {};
    if (message.history?.length) {
      obj.history = message.history.map((e) => TaskHistory.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<TaskHistoryResponse>): TaskHistoryResponse {
    return TaskHistoryResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TaskHistoryResponse>): TaskHistoryResponse {
    const message = createBaseTaskHistoryResponse();
    message.history = object.history?.map((e) => TaskHistory.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
