// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: task_service.proto

/* eslint-disable */
import { Empty } from "./common";
import { CreateLabelRequest, DeleteLabelRequest, LabelResponse, LabelsResponse, UpdateLabelRequest } from "./label";
import {
  CompleteTaskRequest,
  CreateTaskRequest,
  DeleteTaskRequest,
  GetCompletedTasksRequest,
  GetTaskHistoryRequest,
  GetTaskRequest,
  SkipTaskRequest,
  TaskHistoryResponse,
  TaskResponse,
  TasksResponse,
  UncompleteTaskRequest,
  UpdateDueDateRequest,
  UpdateTaskRequest,
} from "./task";
import {
  AppTokenResponse,
  AppTokensResponse,
  AuthResponse,
  ChangePasswordRequest,
  CreateAppTokenRequest,
  DeleteAppTokenRequest,
  LoginRequest,
  RefreshTokenRequest,
  ResetPasswordRequest,
  SignUpRequest,
  UpdateNotificationSettingsRequest,
  UpdatePasswordRequest,
  UserProfileResponse,
} from "./user";

export type TaskServiceDefinition = typeof TaskServiceDefinition;
export const TaskServiceDefinition = {
  name: "TaskService",
  fullName: "com.dkhalife.tasks.grpc.TaskService",
  methods: {
    getTasks: {
      name: "GetTasks",
      requestType: Empty,
      requestStream: false,
      responseType: TasksResponse,
      responseStream: false,
      options: {},
    },
    getCompletedTasks: {
      name: "GetCompletedTasks",
      requestType: GetCompletedTasksRequest,
      requestStream: false,
      responseType: TasksResponse,
      responseStream: false,
      options: {},
    },
    getTask: {
      name: "GetTask",
      requestType: GetTaskRequest,
      requestStream: false,
      responseType: TaskResponse,
      responseStream: false,
      options: {},
    },
    createTask: {
      name: "CreateTask",
      requestType: CreateTaskRequest,
      requestStream: false,
      responseType: TaskResponse,
      responseStream: false,
      options: {},
    },
    updateTask: {
      name: "UpdateTask",
      requestType: UpdateTaskRequest,
      requestStream: false,
      responseType: TaskResponse,
      responseStream: false,
      options: {},
    },
    deleteTask: {
      name: "DeleteTask",
      requestType: DeleteTaskRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    completeTask: {
      name: "CompleteTask",
      requestType: CompleteTaskRequest,
      requestStream: false,
      responseType: TaskResponse,
      responseStream: false,
      options: {},
    },
    uncompleteTask: {
      name: "UncompleteTask",
      requestType: UncompleteTaskRequest,
      requestStream: false,
      responseType: TaskResponse,
      responseStream: false,
      options: {},
    },
    skipTask: {
      name: "SkipTask",
      requestType: SkipTaskRequest,
      requestStream: false,
      responseType: TaskResponse,
      responseStream: false,
      options: {},
    },
    updateDueDate: {
      name: "UpdateDueDate",
      requestType: UpdateDueDateRequest,
      requestStream: false,
      responseType: TaskResponse,
      responseStream: false,
      options: {},
    },
    getTaskHistory: {
      name: "GetTaskHistory",
      requestType: GetTaskHistoryRequest,
      requestStream: false,
      responseType: TaskHistoryResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export type LabelServiceDefinition = typeof LabelServiceDefinition;
export const LabelServiceDefinition = {
  name: "LabelService",
  fullName: "com.dkhalife.tasks.grpc.LabelService",
  methods: {
    getLabels: {
      name: "GetLabels",
      requestType: Empty,
      requestStream: false,
      responseType: LabelsResponse,
      responseStream: false,
      options: {},
    },
    createLabel: {
      name: "CreateLabel",
      requestType: CreateLabelRequest,
      requestStream: false,
      responseType: LabelResponse,
      responseStream: false,
      options: {},
    },
    updateLabel: {
      name: "UpdateLabel",
      requestType: UpdateLabelRequest,
      requestStream: false,
      responseType: LabelResponse,
      responseStream: false,
      options: {},
    },
    deleteLabel: {
      name: "DeleteLabel",
      requestType: DeleteLabelRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
  },
} as const;

export type UserServiceDefinition = typeof UserServiceDefinition;
export const UserServiceDefinition = {
  name: "UserService",
  fullName: "com.dkhalife.tasks.grpc.UserService",
  methods: {
    getProfile: {
      name: "GetProfile",
      requestType: Empty,
      requestStream: false,
      responseType: UserProfileResponse,
      responseStream: false,
      options: {},
    },
    updateNotificationSettings: {
      name: "UpdateNotificationSettings",
      requestType: UpdateNotificationSettingsRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    changePassword: {
      name: "ChangePassword",
      requestType: ChangePasswordRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
  },
} as const;

export type TokenServiceDefinition = typeof TokenServiceDefinition;
export const TokenServiceDefinition = {
  name: "TokenService",
  fullName: "com.dkhalife.tasks.grpc.TokenService",
  methods: {
    getAppTokens: {
      name: "GetAppTokens",
      requestType: Empty,
      requestStream: false,
      responseType: AppTokensResponse,
      responseStream: false,
      options: {},
    },
    createAppToken: {
      name: "CreateAppToken",
      requestType: CreateAppTokenRequest,
      requestStream: false,
      responseType: AppTokenResponse,
      responseStream: false,
      options: {},
    },
    deleteAppToken: {
      name: "DeleteAppToken",
      requestType: DeleteAppTokenRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
  },
} as const;

export type AuthServiceDefinition = typeof AuthServiceDefinition;
export const AuthServiceDefinition = {
  name: "AuthService",
  fullName: "com.dkhalife.tasks.grpc.AuthService",
  methods: {
    signUp: {
      name: "SignUp",
      requestType: SignUpRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    login: {
      name: "Login",
      requestType: LoginRequest,
      requestStream: false,
      responseType: AuthResponse,
      responseStream: false,
      options: {},
    },
    refreshToken: {
      name: "RefreshToken",
      requestType: RefreshTokenRequest,
      requestStream: false,
      responseType: AuthResponse,
      responseStream: false,
      options: {},
    },
    resetPassword: {
      name: "ResetPassword",
      requestType: ResetPasswordRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    updatePassword: {
      name: "UpdatePassword",
      requestType: UpdatePasswordRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
  },
} as const;
