// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  ApiTokenScope,
  apiTokenScopeFromJSON,
  apiTokenScopeToJSON,
  NotificationProvider,
  NotificationTriggerOptions,
} from "./common";

export interface UserProfile {
  displayName: string;
  notificationSettings: NotificationSettings | undefined;
}

export interface NotificationSettings {
  provider: NotificationProvider | undefined;
  triggers: NotificationTriggerOptions | undefined;
}

export interface AppToken {
  id: number;
  name: string;
  token: string;
  scopes: ApiTokenScope[];
  expiresAt: number;
}

export interface SignUpRequest {
  email: string;
  password: string;
  displayName: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  expiresAt: number;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface ResetPasswordRequest {
  email: string;
}

export interface UpdatePasswordRequest {
  code: string;
  newPassword: string;
}

export interface ChangePasswordRequest {
  newPassword: string;
}

export interface CreateAppTokenRequest {
  name: string;
  scopes: ApiTokenScope[];
  expirationDays: number;
}

export interface DeleteAppTokenRequest {
  id: number;
}

export interface UpdateNotificationSettingsRequest {
  provider: NotificationProvider | undefined;
  triggers: NotificationTriggerOptions | undefined;
}

export interface UserProfileResponse {
  user: UserProfile | undefined;
}

export interface AppTokensResponse {
  tokens: AppToken[];
}

export interface AppTokenResponse {
  token: AppToken | undefined;
}

function createBaseUserProfile(): UserProfile {
  return { displayName: "", notificationSettings: undefined };
}

export const UserProfile: MessageFns<UserProfile> = {
  encode(message: UserProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.displayName !== "") {
      writer.uint32(10).string(message.displayName);
    }
    if (message.notificationSettings !== undefined) {
      NotificationSettings.encode(message.notificationSettings, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.notificationSettings = NotificationSettings.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserProfile {
    return {
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : "",
      notificationSettings: isSet(object.notificationSettings)
        ? NotificationSettings.fromJSON(object.notificationSettings)
        : undefined,
    };
  },

  toJSON(message: UserProfile): unknown {
    const obj: any = {};
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.notificationSettings !== undefined) {
      obj.notificationSettings = NotificationSettings.toJSON(message.notificationSettings);
    }
    return obj;
  },

  create(base?: DeepPartial<UserProfile>): UserProfile {
    return UserProfile.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserProfile>): UserProfile {
    const message = createBaseUserProfile();
    message.displayName = object.displayName ?? "";
    message.notificationSettings = (object.notificationSettings !== undefined && object.notificationSettings !== null)
      ? NotificationSettings.fromPartial(object.notificationSettings)
      : undefined;
    return message;
  },
};

function createBaseNotificationSettings(): NotificationSettings {
  return { provider: undefined, triggers: undefined };
}

export const NotificationSettings: MessageFns<NotificationSettings> = {
  encode(message: NotificationSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.provider !== undefined) {
      NotificationProvider.encode(message.provider, writer.uint32(10).fork()).join();
    }
    if (message.triggers !== undefined) {
      NotificationTriggerOptions.encode(message.triggers, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotificationSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotificationSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.provider = NotificationProvider.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.triggers = NotificationTriggerOptions.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NotificationSettings {
    return {
      provider: isSet(object.provider) ? NotificationProvider.fromJSON(object.provider) : undefined,
      triggers: isSet(object.triggers) ? NotificationTriggerOptions.fromJSON(object.triggers) : undefined,
    };
  },

  toJSON(message: NotificationSettings): unknown {
    const obj: any = {};
    if (message.provider !== undefined) {
      obj.provider = NotificationProvider.toJSON(message.provider);
    }
    if (message.triggers !== undefined) {
      obj.triggers = NotificationTriggerOptions.toJSON(message.triggers);
    }
    return obj;
  },

  create(base?: DeepPartial<NotificationSettings>): NotificationSettings {
    return NotificationSettings.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NotificationSettings>): NotificationSettings {
    const message = createBaseNotificationSettings();
    message.provider = (object.provider !== undefined && object.provider !== null)
      ? NotificationProvider.fromPartial(object.provider)
      : undefined;
    message.triggers = (object.triggers !== undefined && object.triggers !== null)
      ? NotificationTriggerOptions.fromPartial(object.triggers)
      : undefined;
    return message;
  },
};

function createBaseAppToken(): AppToken {
  return { id: 0, name: "", token: "", scopes: [], expiresAt: 0 };
}

export const AppToken: MessageFns<AppToken> = {
  encode(message: AppToken, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.token !== "") {
      writer.uint32(26).string(message.token);
    }
    writer.uint32(34).fork();
    for (const v of message.scopes) {
      writer.int32(v);
    }
    writer.join();
    if (message.expiresAt !== 0) {
      writer.uint32(40).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppToken {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.scopes.push(reader.int32() as any);

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.scopes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.expiresAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AppToken {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => apiTokenScopeFromJSON(e)) : [],
      expiresAt: isSet(object.expiresAt) ? globalThis.Number(object.expiresAt) : 0,
    };
  },

  toJSON(message: AppToken): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes.map((e) => apiTokenScopeToJSON(e));
    }
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    return obj;
  },

  create(base?: DeepPartial<AppToken>): AppToken {
    return AppToken.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AppToken>): AppToken {
    const message = createBaseAppToken();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.token = object.token ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

function createBaseSignUpRequest(): SignUpRequest {
  return { email: "", password: "", displayName: "" };
}

export const SignUpRequest: MessageFns<SignUpRequest> = {
  encode(message: SignUpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.displayName !== "") {
      writer.uint32(26).string(message.displayName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignUpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignUpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignUpRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : "",
    };
  },

  toJSON(message: SignUpRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    return obj;
  },

  create(base?: DeepPartial<SignUpRequest>): SignUpRequest {
    return SignUpRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignUpRequest>): SignUpRequest {
    const message = createBaseSignUpRequest();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    message.displayName = object.displayName ?? "";
    return message;
  },
};

function createBaseLoginRequest(): LoginRequest {
  return { email: "", password: "" };
}

export const LoginRequest: MessageFns<LoginRequest> = {
  encode(message: LoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: LoginRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create(base?: DeepPartial<LoginRequest>): LoginRequest {
    return LoginRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LoginRequest>): LoginRequest {
    const message = createBaseLoginRequest();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseAuthResponse(): AuthResponse {
  return { accessToken: "", refreshToken: "", expiresAt: 0 };
}

export const AuthResponse: MessageFns<AuthResponse> = {
  encode(message: AuthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    if (message.refreshToken !== "") {
      writer.uint32(18).string(message.refreshToken);
    }
    if (message.expiresAt !== 0) {
      writer.uint32(24).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expiresAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthResponse {
    return {
      accessToken: isSet(object.accessToken) ? globalThis.String(object.accessToken) : "",
      refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "",
      expiresAt: isSet(object.expiresAt) ? globalThis.Number(object.expiresAt) : 0,
    };
  },

  toJSON(message: AuthResponse): unknown {
    const obj: any = {};
    if (message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    return obj;
  },

  create(base?: DeepPartial<AuthResponse>): AuthResponse {
    return AuthResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuthResponse>): AuthResponse {
    const message = createBaseAuthResponse();
    message.accessToken = object.accessToken ?? "";
    message.refreshToken = object.refreshToken ?? "";
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

function createBaseRefreshTokenRequest(): RefreshTokenRequest {
  return { refreshToken: "" };
}

export const RefreshTokenRequest: MessageFns<RefreshTokenRequest> = {
  encode(message: RefreshTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.refreshToken !== "") {
      writer.uint32(10).string(message.refreshToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshTokenRequest {
    return { refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "" };
  },

  toJSON(message: RefreshTokenRequest): unknown {
    const obj: any = {};
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    return obj;
  },

  create(base?: DeepPartial<RefreshTokenRequest>): RefreshTokenRequest {
    return RefreshTokenRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RefreshTokenRequest>): RefreshTokenRequest {
    const message = createBaseRefreshTokenRequest();
    message.refreshToken = object.refreshToken ?? "";
    return message;
  },
};

function createBaseResetPasswordRequest(): ResetPasswordRequest {
  return { email: "" };
}

export const ResetPasswordRequest: MessageFns<ResetPasswordRequest> = {
  encode(message: ResetPasswordRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetPasswordRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetPasswordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResetPasswordRequest {
    return { email: isSet(object.email) ? globalThis.String(object.email) : "" };
  },

  toJSON(message: ResetPasswordRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create(base?: DeepPartial<ResetPasswordRequest>): ResetPasswordRequest {
    return ResetPasswordRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResetPasswordRequest>): ResetPasswordRequest {
    const message = createBaseResetPasswordRequest();
    message.email = object.email ?? "";
    return message;
  },
};

function createBaseUpdatePasswordRequest(): UpdatePasswordRequest {
  return { code: "", newPassword: "" };
}

export const UpdatePasswordRequest: MessageFns<UpdatePasswordRequest> = {
  encode(message: UpdatePasswordRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.newPassword !== "") {
      writer.uint32(18).string(message.newPassword);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdatePasswordRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePasswordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.newPassword = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePasswordRequest {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      newPassword: isSet(object.newPassword) ? globalThis.String(object.newPassword) : "",
    };
  },

  toJSON(message: UpdatePasswordRequest): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.newPassword !== "") {
      obj.newPassword = message.newPassword;
    }
    return obj;
  },

  create(base?: DeepPartial<UpdatePasswordRequest>): UpdatePasswordRequest {
    return UpdatePasswordRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdatePasswordRequest>): UpdatePasswordRequest {
    const message = createBaseUpdatePasswordRequest();
    message.code = object.code ?? "";
    message.newPassword = object.newPassword ?? "";
    return message;
  },
};

function createBaseChangePasswordRequest(): ChangePasswordRequest {
  return { newPassword: "" };
}

export const ChangePasswordRequest: MessageFns<ChangePasswordRequest> = {
  encode(message: ChangePasswordRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.newPassword !== "") {
      writer.uint32(10).string(message.newPassword);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangePasswordRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangePasswordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.newPassword = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangePasswordRequest {
    return { newPassword: isSet(object.newPassword) ? globalThis.String(object.newPassword) : "" };
  },

  toJSON(message: ChangePasswordRequest): unknown {
    const obj: any = {};
    if (message.newPassword !== "") {
      obj.newPassword = message.newPassword;
    }
    return obj;
  },

  create(base?: DeepPartial<ChangePasswordRequest>): ChangePasswordRequest {
    return ChangePasswordRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChangePasswordRequest>): ChangePasswordRequest {
    const message = createBaseChangePasswordRequest();
    message.newPassword = object.newPassword ?? "";
    return message;
  },
};

function createBaseCreateAppTokenRequest(): CreateAppTokenRequest {
  return { name: "", scopes: [], expirationDays: 0 };
}

export const CreateAppTokenRequest: MessageFns<CreateAppTokenRequest> = {
  encode(message: CreateAppTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    writer.uint32(18).fork();
    for (const v of message.scopes) {
      writer.int32(v);
    }
    writer.join();
    if (message.expirationDays !== 0) {
      writer.uint32(24).int32(message.expirationDays);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAppTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAppTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.scopes.push(reader.int32() as any);

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.scopes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expirationDays = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateAppTokenRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => apiTokenScopeFromJSON(e)) : [],
      expirationDays: isSet(object.expirationDays) ? globalThis.Number(object.expirationDays) : 0,
    };
  },

  toJSON(message: CreateAppTokenRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes.map((e) => apiTokenScopeToJSON(e));
    }
    if (message.expirationDays !== 0) {
      obj.expirationDays = Math.round(message.expirationDays);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateAppTokenRequest>): CreateAppTokenRequest {
    return CreateAppTokenRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateAppTokenRequest>): CreateAppTokenRequest {
    const message = createBaseCreateAppTokenRequest();
    message.name = object.name ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    message.expirationDays = object.expirationDays ?? 0;
    return message;
  },
};

function createBaseDeleteAppTokenRequest(): DeleteAppTokenRequest {
  return { id: 0 };
}

export const DeleteAppTokenRequest: MessageFns<DeleteAppTokenRequest> = {
  encode(message: DeleteAppTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteAppTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteAppTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteAppTokenRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: DeleteAppTokenRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteAppTokenRequest>): DeleteAppTokenRequest {
    return DeleteAppTokenRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteAppTokenRequest>): DeleteAppTokenRequest {
    const message = createBaseDeleteAppTokenRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseUpdateNotificationSettingsRequest(): UpdateNotificationSettingsRequest {
  return { provider: undefined, triggers: undefined };
}

export const UpdateNotificationSettingsRequest: MessageFns<UpdateNotificationSettingsRequest> = {
  encode(message: UpdateNotificationSettingsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.provider !== undefined) {
      NotificationProvider.encode(message.provider, writer.uint32(10).fork()).join();
    }
    if (message.triggers !== undefined) {
      NotificationTriggerOptions.encode(message.triggers, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateNotificationSettingsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateNotificationSettingsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.provider = NotificationProvider.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.triggers = NotificationTriggerOptions.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateNotificationSettingsRequest {
    return {
      provider: isSet(object.provider) ? NotificationProvider.fromJSON(object.provider) : undefined,
      triggers: isSet(object.triggers) ? NotificationTriggerOptions.fromJSON(object.triggers) : undefined,
    };
  },

  toJSON(message: UpdateNotificationSettingsRequest): unknown {
    const obj: any = {};
    if (message.provider !== undefined) {
      obj.provider = NotificationProvider.toJSON(message.provider);
    }
    if (message.triggers !== undefined) {
      obj.triggers = NotificationTriggerOptions.toJSON(message.triggers);
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateNotificationSettingsRequest>): UpdateNotificationSettingsRequest {
    return UpdateNotificationSettingsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateNotificationSettingsRequest>): UpdateNotificationSettingsRequest {
    const message = createBaseUpdateNotificationSettingsRequest();
    message.provider = (object.provider !== undefined && object.provider !== null)
      ? NotificationProvider.fromPartial(object.provider)
      : undefined;
    message.triggers = (object.triggers !== undefined && object.triggers !== null)
      ? NotificationTriggerOptions.fromPartial(object.triggers)
      : undefined;
    return message;
  },
};

function createBaseUserProfileResponse(): UserProfileResponse {
  return { user: undefined };
}

export const UserProfileResponse: MessageFns<UserProfileResponse> = {
  encode(message: UserProfileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      UserProfile.encode(message.user, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserProfileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserProfileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = UserProfile.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserProfileResponse {
    return { user: isSet(object.user) ? UserProfile.fromJSON(object.user) : undefined };
  },

  toJSON(message: UserProfileResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = UserProfile.toJSON(message.user);
    }
    return obj;
  },

  create(base?: DeepPartial<UserProfileResponse>): UserProfileResponse {
    return UserProfileResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserProfileResponse>): UserProfileResponse {
    const message = createBaseUserProfileResponse();
    message.user = (object.user !== undefined && object.user !== null)
      ? UserProfile.fromPartial(object.user)
      : undefined;
    return message;
  },
};

function createBaseAppTokensResponse(): AppTokensResponse {
  return { tokens: [] };
}

export const AppTokensResponse: MessageFns<AppTokensResponse> = {
  encode(message: AppTokensResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tokens) {
      AppToken.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppTokensResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppTokensResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tokens.push(AppToken.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AppTokensResponse {
    return {
      tokens: globalThis.Array.isArray(object?.tokens) ? object.tokens.map((e: any) => AppToken.fromJSON(e)) : [],
    };
  },

  toJSON(message: AppTokensResponse): unknown {
    const obj: any = {};
    if (message.tokens?.length) {
      obj.tokens = message.tokens.map((e) => AppToken.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<AppTokensResponse>): AppTokensResponse {
    return AppTokensResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AppTokensResponse>): AppTokensResponse {
    const message = createBaseAppTokensResponse();
    message.tokens = object.tokens?.map((e) => AppToken.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAppTokenResponse(): AppTokenResponse {
  return { token: undefined };
}

export const AppTokenResponse: MessageFns<AppTokenResponse> = {
  encode(message: AppTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== undefined) {
      AppToken.encode(message.token, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = AppToken.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AppTokenResponse {
    return { token: isSet(object.token) ? AppToken.fromJSON(object.token) : undefined };
  },

  toJSON(message: AppTokenResponse): unknown {
    const obj: any = {};
    if (message.token !== undefined) {
      obj.token = AppToken.toJSON(message.token);
    }
    return obj;
  },

  create(base?: DeepPartial<AppTokenResponse>): AppTokenResponse {
    return AppTokenResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AppTokenResponse>): AppTokenResponse {
    const message = createBaseAppTokenResponse();
    message.token = (object.token !== undefined && object.token !== null)
      ? AppToken.fromPartial(object.token)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
