name: API Build

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apiserver/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'apiserver/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        check-latest: true
        cache: true

    - name: Build
      run: |
        cd apiserver
        VERSION=$(date -u +'%y%m%d').00.1
        go build -v \
          -ldflags "-X dkhalife.com/tasks/core/internal/version.Version=${VERSION} \
                    -X dkhalife.com/tasks/core/internal/version.BuildNumber=0 \
                    -X dkhalife.com/tasks/core/internal/version.CommitHash=${{ github.sha }}" \
          ./...

    - name: Install lint tool
      run: |
        cd apiserver
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Lint
      run: |
        cd apiserver
        golangci-lint run

    - name: Run Tests and Generate Coverage
      run: |
        cd apiserver
        go test -v -coverprofile=coverage.txt ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
