name: Frontend Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Enable Corepack
      run: corepack enable
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock
    - name: Install dependencies
      run: yarn install --immutable
      working-directory: frontend
    - name: Lint
      run: yarn lint
      working-directory: frontend
    - name: Build (TSC)
      run: yarn tsc
      working-directory: frontend
    - name: Build (Vite)
      run: yarn build
      working-directory: frontend
    - name: Run unit tests
      run: yarn test
      working-directory: frontend
    - name: Install Playwright Browsers
      if: github.event_name == 'push'
      run: npx playwright install --with-deps chromium
      working-directory: frontend
    - name: Run Playwright tests
      if: github.event_name == 'push'
      run: yarn test:e2e
      working-directory: frontend
    - uses: actions/upload-artifact@v4
      if: github.event_name == 'push' && always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
